version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cloudprojectchinmay"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-18khd9mqdxgh6"
s3_prefix = "cloudprojectchinmay"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "InputBucketName=\"mycloudprojectbucket\""
confirm_changeset = true
